load("@rules_verilator//verilator/internal:toolchain.bzl", "verilator_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

verilator_toolchain_alias(
    name = "toolchain",
    visibility = ["//visibility:public"],
)
